### ISSUE TITLE
Форма обратной связи на странице "как заказать проект"

### ISSUE THREAD

**Issue by coxa** [tpotapchik/Houses#4]
траничка находится тут http://dom-tut.by/catalog/pages/order-project
шаблон тут `/web/themes/houses/views/catalog/orderProject.php`
Нужно сверстать простую форму обратной связи. Очень прошу сделать это вне блока
`<div class="main-text-block ovhidden">`

**Comment by tpotapchik** [comment]
Коля, надо проверить валидацию на js (а то ты прошлую мою переделал)
и подправить, если надо файл php

**Comment by coxa** [comment]
принимаю
